backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"   # uploaded assets go to /public
public_folder: "/uploads"

publish_mode: simple

collections:
  # Programs Collection
  - name: "programs"
    label: "Programs"
    folder: "src/content/programs"
    create: true
    slug: "{{slug}}"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Program Title", name: "title", widget: "string" }
      - { label: "Age Range", name: "age_range", widget: "string", hint: "e.g., 0-12 months, 12-36 months, 36+ months" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Teacher : Child Ratio", name: "ratio", widget: "string", hint: "e.g., 1:4" }
      - label: "Tuition (Monthly)"
        name: "tuition"
        widget: "object"
        fields:
          - { label: "Full Time", name: "full_time", widget: "number", value_type: "float", min: 0 }
          - { label: "Part Time", name: "part_time", widget: "number", value_type: "float", required: false }
          - { label: "Drop-in (daily)", name: "drop_in", widget: "number", value_type: "float", required: false }
      - label: "Availability"
        name: "availability"
        widget: "object"
        fields:
          - { label: "Status", name: "status", widget: "select", options: ["Openings", "Waitlist", "Full"], default: "Waitlist" }
          - { label: "Max Capacity", name: "max_capacity", widget: "number", value_type: "int", min: 0, default: 0, hint: "Maximum number of kids allowed in this program" }
          - { label: "Kids Enrolled", name: "enrolled", widget: "number", value_type: "int", min: 0, default: 0 }
          # CMS can't compute fields; keep optional. UI will compute if omitted.
          - { label: "Open Spots (optional)", name: "open_spots", widget: "number", value_type: "int", required: false, min: 0 }
          - { label: "Next Opening", name: "next_opening", widget: "datetime", required: false, date_format: "YYYY-MM-DD", time_format: false }

  # Closures Collection
  - name: "closures"
    label: "Closures & Holidays"
    folder: "src/content/closures"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "e.g., Labor Day" }
      - { label: "Start Date", name: "start", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "End Date", name: "end", widget: "datetime", required: false, date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Description", name: "description", widget: "text", required: false }

# Site-wide Settings (singleton files)
-name: "settings"
label: "Site Settings"
files:
  - label: "Billing & Attendance"
    name: "billing"
    file: "src/content/settings/billing.json"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Enable Brightwheel Disclaimer", name: "enabled", widget: "boolean", default: true }
      - { label: "Hourly Threshold (hours)", name: "threshold_hours", widget: "number", value_type: "float", min: 0, step: 0.25, default: 4 }
      - { label: "Rate up to Threshold (per day)", name: "rate_under_or_equal", widget: "number", value_type: "float", min: 0, default: 30 }
      - { label: "Rate over Threshold (per day)", name: "rate_over", widget: "number", value_type: "float", min: 0, default: 60 }
      - { label: "Extra Notes (optional)", name: "notes", widget: "text", required: false, hint: "E.g., 'Before/after-school follows the same time-based pricing.'" }




  # Documents Collection
  - name: "documents"
    label: "Documents"
    folder: "src/content/documents"
    create: true
    slug: "{{slug}}"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }
      - { label: "Description", name: "description", widget: "string", required: false }

  # Information Collection
  - name: "information"
    label: "Bulletin Board"
    folder: "src/content/information"
    create: true
    slug: "{{slug}}"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }




#About.tsx Page for Staff
  - name: "staff"
    label: "Staff"
    folder: "src/content/staff"
    create: true
    slug: "{{slug}}"
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image", required: false, hint: "Uploads go to /uploads; value will be like /uploads/jane.jpg" }
      - { label: "Sort Order", name: "order", widget: "number", value_type: "int", default: 0, hint: "Lower = appears first" }
      # Optional: badges if you re-enable them later
      - { label: "Badges", name: "badges", widget: "list", required: false }
