backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # Where uploaded media files will be stored
public_folder: "/uploads"     # Public URL for accessing uploaded media files

publish_mode: simple

collections:
  # Programs Collection
  - name: "programs"
    label: "Programs"
    folder: "public/content/programs" # Save each program as a separate JSON file in public/content/programs
    create: true
    slug: "{{slug}}" # Create files with a slug based on the program title
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Program Title", name: "title", widget: "string" }
      - { label: "Age Range", name: "age_range", widget: "string", hint: "e.g., 0–12 months, 12–36 months, 36+ months" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Teacher : Child Ratio", name: "ratio", widget: "string", hint: "e.g., 1:4" }
      - label: "Tuition (Monthly)"
        name: "tuition"
        widget: "object"
        fields:
          - { label: "Full Time", name: "full_time", widget: "number", value_type: "float", min: 0 }
          - { label: "Part Time", name: "part_time", widget: "number", value_type: "float", required: false }
          - { label: "Drop-in (daily)", name: "drop_in", widget: "number", value_type: "float", required: false }
      - label: "Availability"
        name: "availability"
        widget: "object"
        fields:
          - { label: "Status", name: "status", widget: "select", options: ["Openings", "Waitlist", "Full"], default: "Waitlist" }
          - { label: "Max Capacity", name: "max_capacity", widget: "number", value_type: "int", min: 0, default: 0, hint: "Maximum number of kids allowed in this program" }
          - { label: "Kids Enrolled", name: "enrolled", widget: "number", value_type: "int", min: 0, default: 0 }
          - { label: "Open Spots", name: "open_spots", widget: "calculated", calculate: "max_capacity - enrolled", value_type: "int", min: 0 }
          - { label: "Next Opening", name: "next_opening", widget: "datetime", required: false, date_format: "YYYY-MM-DD", time_format: false }

  # Closures Collection
  - name: "closures"
    label: "Closures & Holidays"
    folder: "public/content/closures" # Save each closure as a separate JSON file in public/content/closures
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Use date-based slugs for closures
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "e.g., Labor Day" }
      - { label: "Start Date", name: "start", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "End Date", name: "end", widget: "datetime", required: false, date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Description", name: "description", widget: "text", required: false }

  # Documents Collection
  - name: "documents"
    label: "Documents"
    folder: "public/content/documents" # Save documents.json file in public/content/documents
    create: true
    slug: "{{slug}}" # Create files with a slug based on the document title
    format: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }
      - { label: "Description", name: "description", widget: "string", required: false }